// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXdGPktMh1Jwft4sIeJVV-L7fTSZWmYeQ',
    appId: '1:567875532581:web:01cbf1a6040ef843ae8ccc',
    messagingSenderId: '567875532581',
    projectId: 'ninja-brew-crew-d5d53',
    authDomain: 'ninja-brew-crew-d5d53.firebaseapp.com',
    storageBucket: 'ninja-brew-crew-d5d53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsKxd0t149y2CAy7mmGYlKMJgnnV2uau8',
    appId: '1:567875532581:android:f298df0b4ba41d84ae8ccc',
    messagingSenderId: '567875532581',
    projectId: 'ninja-brew-crew-d5d53',
    storageBucket: 'ninja-brew-crew-d5d53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGIsCr-MonX85EiaExzw0OLSbohwlXJw8',
    appId: '1:567875532581:ios:7755d7a026ab4c14ae8ccc',
    messagingSenderId: '567875532581',
    projectId: 'ninja-brew-crew-d5d53',
    storageBucket: 'ninja-brew-crew-d5d53.appspot.com',
    iosClientId: '567875532581-qjomgl3amfst9asfg3ghq9ikq07hdlu8.apps.googleusercontent.com',
    iosBundleId: 'com.codeconline.com.ninjaBrewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGIsCr-MonX85EiaExzw0OLSbohwlXJw8',
    appId: '1:567875532581:ios:7755d7a026ab4c14ae8ccc',
    messagingSenderId: '567875532581',
    projectId: 'ninja-brew-crew-d5d53',
    storageBucket: 'ninja-brew-crew-d5d53.appspot.com',
    iosClientId: '567875532581-qjomgl3amfst9asfg3ghq9ikq07hdlu8.apps.googleusercontent.com',
    iosBundleId: 'com.codeconline.com.ninjaBrewCrew',
  );
}
